---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-secret
spec:
  description: >-
    Simple directory lister
  steps:
    - name: list-directory
      image: busybox
      command:
        - env
      env:
        - name: AUTH_JSON
          valueFrom:
            secretKeyRef:
              name: 'cytan-pull-secret'
              key: '.dockerconfigjson'